---
- hosts: All
#  gather_facts: False

  tasks:
    - name: Getting file
      shell: "cp /builds/manageiq/{{ release }}/{{ version }}/manageiq-vsphere*.ova {{ version }}.ova"

    - name: Deploying OVA File
      vmware_deploy_ovf:
        hostname: '{{ myhost }}'
        username: '{{ redhatID }}'
        password: '{{ redhatPass }}'
        cluster: dev-vc67-cluster
        datacenter: dev-vc67-DC
        datastore: NFS Share
        ovf: "{{ version }}.ova"
        allow_duplicates: no
        validate_certs: no
        name: '{{ newvm }}'
        power_on: no
      delegate_to: localhost

    - name: Powering on appliance
      vmware_guest:
        hostname: '{{ myhost }}'
        username: '{{ redhatID }}'
        password: '{{ redhatPass }}'
        validate_certs: no
        name: '{{ newvm }}'
        state: poweredon
        wait_for_ip_address: True
      delegate_to: localhost
      register: deployInfo

    - name: Gathering facts of appliance
      setup:
      register: moreInfo
      delegate_to: '{{ deployInfo.instance.hw_eth0.ipaddresses[0] }}'

    - name: ManageIQ - Starting EVM service manually
      shell: systemctl start evmserverd.service
      delegate_to: '{{ deployInfo.instance.hw_eth0.ipaddresses[0] }}'

    - debug:
        msg: "You should now be able to access your appliance via https://{{ deployInfo.instance.hw_eth0.ipaddresses[0] }} Please allow roughly 15 minutes for the service to fully come online."
